baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'julianwest.me.blog'
theme = 'gokarna'
weight = 1
pluralizeListTitles = false
enableRobotsTXT = true

defaultContentLanguage = "en"
#sectionPagesMenu = "main"

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[menus]
  [[menus.main]]
    name = 'Main'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = "Tags"
    url = "/tags/"
    weight = 25
  [[menus.main]]
    name = 'About'
    pageRef = '/about/about'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact/contacting'
    weight = 40
  [[menus.main]]
    identifier = "github"
    url = "https://github.com/J-DubApps"
    weight = 50
  [[menus.footer]]
    name = 'Colophon'
    pageRef = '/colophon/colophon'
    weight = 10
  [[menus.footer]]
    name = 'Terms'
    pageRef = '/site-disclosure'
    weight = 20

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Julian West"
favicon = ""
site_logo = ""
description = "julianwest.me.blog"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 5

  # Choose the color shown when hyperlinks are hovered over
  accentColor = "#FF4D4D"

  # Resource URL for the site avatar (home page and header)
  avatarURL = "/public/images/avatar.jpeg"

  # Describe the avatar for screen readers
  avatarAltText = "avatar"

  # Set the avatar's size: size-xs, size-s, size-m, size-l & size-xl
  avatarSize = "size-m"

  # Inject arbitrary HTML via the <head> tag
  # Best used for importing custom JavaScript, CSS, or analytics
  customHeadHTML = ""

  # Configure how post dates are displayed
  # dateFormat must be set if lastmod is declared in front matter, or
  # enableGitInfo is true
  dateFormat = "January 2, 2006"
  
  # Home page meta description
  description = "Sky above, sand below & peace within"

  # Footer text (i.e. author/project name)
  footer = "The Marauders"

  # Define SEO keywords
  metaKeywords = ["blog", "gokarna", "hugo"]

  # Define how many posts are displayed on the home page
  # showPostsOnHomePage must be "popular" or "recent"
  numberPostsOnHomePage = 4

  # Display a "back to top" button on posts and pages: true, false
  # May not render on smaller screen sizes
  showBackToTopButton = true

  # Display posts on the home page:
  # "popular" (order posts by weight)
  # "recent" (order posts by date)
  # "", unset (do not display)
  showPostsOnHomePage = ""

  # Show the previous and next post in your timeline: "true", "false"
  # Incompatible with Weight
  togglePreviousAndNextButtons = "false"