baseURL = 'http://julianwest.me/Blog/'
languageCode = 'en-us'
title = 'julianwest.me.blog'
theme = ["github.com/J-DubApps/Blog/tree/main/themes/gokarna"]
weight = 1
pluralizeListTitles = false
enableRobotsTXT = false

defaultContentLanguage = "en"
#sectionPagesMenu = "main"

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
  
[menus]
  [[menus.main]]
    name = 'Julianwest.me'
    url = "https://julianwest.me"
    weight = 10
  [[menus.main]]
    name = 'Main'
    url = "https://julianwest.me/Blog"
    weight = 15
  [[menus.main]]
    name = 'Posts'
    pre = "<i class='fa fa-list' aria-hidden='true'></i>"
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/about/about'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact/contacting'
    weight = 40
  [[menus.main]]
    name = "Tags"
    url = "/tags/"
    weight = 45
  [[menus.main]]
    mame = 'Github'
    identifier = "github"
    url = "https://github.com/J-DubApps"
    weight = 50
  [[menus.footer]]
    name = 'Colophon'
    pageRef = '/colophon/colophon'
    weight = 10
  [[menus.footer]]
    name = 'Terms'
    pageRef = '/site-disclosure'
    weight = 20

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Julian West"
favicon = "/images/favicon/favicon.ico"
site_logo = ""
description = "julianwest.me.blog"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 5


avatarAltText = "avatar"
avatarSize = "size-l"
avatarURL = "/images/avatar.jpeg"
footer = "julianwest.me"
metaKeywords = ["blog", "julianwest.me", "julian west"]
