baseURL = 'http://julianwest.me/Blog/'
languageCode = 'en-us'
title = 'julianwest.me.blog'
theme = 'ananke'
weight = 1
pluralizeListTitles = false

defaultContentLanguage = "en"
# sectionPagesMenu = "main"

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Articles'
    pageRef = '/posts'
    weight = 20

[params]
text_color = ""
author = "Julian West"
favicon = ""
site_logo = ""
description = "julianwest.me.blog"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 5


[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.facebook]
username = "west.julian"
# profilelink = "https://www.facebook.com/west.julian"

[params.ananke.social.linkedin]
username = "julianwest"

[params.ananke.social.bluesky]
username = "julianwest.me"